module.exports = [
  "10 easy and quick dinner recipes for home",
  "The best vegetarian restaurants in town",
  "How to make your own bread at home",
  "The secrets of Italian cooking",
  "The art of sushi: how to make it at home",
  "The history of chocolate: from the Mayans to today",
  "Typical wines from each region of Spain",
  "How to make your own cheese at home",
  "The benefits of eating organic food",
  "The best typical dishes from each country",
  "The world of olive oils: varieties and uses",
  "How to make your own BBQ sauce",
  "The art of tea: history and varieties",
  "The best cafes in town",
  "How to make your own wine at home",
  "The history of wine: from the Egyptians to today",
  "The benefits of Mediterranean food",
  "The best desserts in the region",
  "How to make your own goat cheese at home",
  "The secrets of French cooking",
  "The world of cheeses: varieties and uses",
  "How to make your own beer at home",
  "The history of coffee: from Ethiopia to today",
  "The best outdoor dining spots in town",
  "How to make your own olive oil at home",
  "The secrets of Asian cooking",
  "The world of wines: varieties and pairings",
  "How to make your own honey at home",
  "The history of tea: from China to today",
  "The best Michelin-starred restaurants in the region",
];
